extends RefCounted
# class_name omitted so this draft does not clash with data/campaign_board.gd

# AUTO-GENERATED from screenshots - ALL levels replaced
# Generated by extract_all_levels.py

const LevelDefinitionScript = preload("res://data/level_definition.gd")
const PieceDefinitionScript = preload("res://data/piece_definition.gd")
const GapDefinitionScript = preload("res://data/gap_definition.gd")
const LinkDefinitionScript = preload("res://data/link_definition.gd")
const SolutionStepScript = preload("res://data/solution_step.gd")
const Rules = preload("res://gameplay/puzzle_rules.gd")
const Geometry = preload("res://gameplay/piece_geometry.gd")
const RingPiece2DScript = preload("res://gameplay/ring_piece_2d.gd")
const ConnectorRuntime = preload("res://gameplay/connector_runtime.gd")
const BFSSolver = preload("res://tools/bfs_solver.gd")

const C := 0  # Circle
const S := 1  # Square
const T := 2  # Triangle
const O := 3  # Oval

const _PALETTE: Array[Color] = [
	Color("#32ADDA"),  # Cyan
	Color("#EA7829"),  # Orange
	Color("#7B61FF"),  # Purple
	Color("#C8202F"),  # Red
	Color("#2CA45C"),  # Green
	Color("#4361CF"),  # Blue
	Color("#F38224"),  # Light Orange
	Color("#3EC6B0"),  # Teal
]

const _BOARD := Vector2(360, 610)
const _HALF := Vector2(292, 370)
const _AIR := 34.0

static var _cache: Dictionary = {}
static var _defer_solve: bool = true

static func build(level_id: int):
	if _cache.has(level_id):
		return _cache[level_id]
	var spec: Dictionary = _spec(level_id)
	var root: Dictionary = spec.root
	_paint(root, level_id % _PALETTE.size(), -1)
	var flat: Array = []
	var edges: Array = []
	_walk(root, Vector2.ZERO, flat, edges)
	_fit(flat)
	var def = LevelDefinitionScript.new()
	def.level_id = level_id
	def.chapter_id = 1 + int((level_id - 1) / 10)
	def.title = spec.title
	def.instruction = spec.instruction
	def.pieces = _pieces_from(flat)
	def.links = _links_from(flat, edges)
	_set_rest_angles(def)
	_stamp_solution(def)
	_cache[level_id] = def
	return def

static func _spec(level_id: int) -> Dictionary:
	return _level_root(level_id)

static func _level_root(level_id: int) -> Dictionary:
	# All levels extracted from screenshots
	match level_id:
		2:
			# Level 2
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.51 PM.jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 2",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		3:
			# Level 3
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.55 PM (1).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 3",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		4:
			# Level 4
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.55 PM (2).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 4",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		5:
			# Level 5
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.55 PM (3).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 5",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		6:
			# Level 6
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.55 PM (4).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 6",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		7:
			# Level 7
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.55 PM (5).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 7",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		8:
			# Level 8
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.55 PM.jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 8",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		9:
			# Level 9
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.56 PM (1).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 9",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		10:
			# Level 10
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.56 PM (2).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 10",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		11:
			# Level 11
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.56 PM (3).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 11",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		12:
			# Level 12
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.56 PM.jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 12",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		13:
			# Level 13
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (1).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 13",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		14:
			# Level 14
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (10).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 14",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		15:
			# Level 15
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (11).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 15",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		16:
			# Level 16
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (12).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 16",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		17:
			# Level 17
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (13).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 17",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		18:
			# Level 18
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (14).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 18",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		19:
			# Level 19
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (15).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 19",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		20:
			# Level 20
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (16).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 20",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		21:
			# Level 21
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (17).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 21",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		22:
			# Level 22
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (18).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 22",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		23:
			# Level 23
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (19).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 23",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		24:
			# Level 24
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (2).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 24",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		25:
			# Level 25
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (3).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 25",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		26:
			# Level 26
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (4).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 26",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		27:
			# Level 27
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (5).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 27",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		28:
			# Level 28
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (6).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 28",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		29:
			# Level 29
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (7).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 29",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		30:
			# Level 30
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (8).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 30",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		31:
			# Level 31
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM (9).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 31",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		32:
			# Level 32
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.58 PM.jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 32",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		33:
			# Level 33
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.59 PM (1).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 33",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		34:
			# Level 34
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.59 PM (2).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 34",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		35:
			# Level 35
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.59 PM (3).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 35",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		36:
			# Level 36
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.59 PM (4).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 36",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		37:
			# Level 37
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.59 PM (5).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 37",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		38:
			# Level 38
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.59 PM (6).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 38",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		39:
			# Level 39
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.59 PM (7).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 39",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		40:
			# Level 40
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.59 PM (8).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 40",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		41:
			# Level 41
			# Screenshot: WhatsApp Image 2026-10-06 at 6.46.59 PM.jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 41",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		42:
			# Level 42
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (1).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 42",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		43:
			# Level 43
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (10).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 43",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		44:
			# Level 44
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (11).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 44",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		45:
			# Level 45
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (12).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 45",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		46:
			# Level 46
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (13).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 46",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		47:
			# Level 47
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (14).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 47",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		48:
			# Level 48
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (15).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 48",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		49:
			# Level 49
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (16).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 49",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		50:
			# Level 50
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (17).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 50",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		51:
			# Level 51
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (18).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 51",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		52:
			# Level 52
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (19).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 52",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		53:
			# Level 53
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (2).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 53",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		54:
			# Level 54
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (20).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 54",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		55:
			# Level 55
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (21).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 55",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		56:
			# Level 56
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (22).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 56",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		57:
			# Level 57
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (23).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 57",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		58:
			# Level 58
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (24).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 58",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		59:
			# Level 59
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (25).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 59",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		60:
			# Level 60
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (26).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 60",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		61:
			# Level 61
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (27).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 61",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		62:
			# Level 62
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (28).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 62",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		63:
			# Level 63
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (29).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 63",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		64:
			# Level 64
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (3).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 64",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		65:
			# Level 65
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (30).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 65",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		66:
			# Level 66
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (31).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 66",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		67:
			# Level 67
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (32).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 67",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		68:
			# Level 68
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (33).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 68",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		69:
			# Level 69
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (34).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 69",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		70:
			# Level 70
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (35).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 70",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		71:
			# Level 71
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (36).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 71",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		72:
			# Level 72
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (37).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 72",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		73:
			# Level 73
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (38).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 73",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		74:
			# Level 74
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (39).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 74",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		75:
			# Level 75
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (4).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 75",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		76:
			# Level 76
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (40).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 76",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		77:
			# Level 77
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (41).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 77",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		78:
			# Level 78
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (42).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 78",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		79:
			# Level 79
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (43).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 79",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		80:
			# Level 80
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (44).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 80",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		81:
			# Level 81
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (45).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 81",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		82:
			# Level 82
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (46).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 82",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		83:
			# Level 83
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (47).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 83",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		84:
			# Level 84
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (5).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 84",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		85:
			# Level 85
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (6).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 85",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		86:
			# Level 86
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (7).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 86",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		87:
			# Level 87
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (8).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 87",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		88:
			# Level 88
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM (9).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 88",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		89:
			# Level 89
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.00 PM.jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 89",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		90:
			# Level 90
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.01 PM (1).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 90",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		91:
			# Level 91
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.01 PM (10).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 91",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		92:
			# Level 92
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.01 PM (2).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 92",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		93:
			# Level 93
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.01 PM (3).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 93",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		94:
			# Level 94
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.01 PM (4).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 94",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		95:
			# Level 95
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.01 PM (5).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 95",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		96:
			# Level 96
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.01 PM (6).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 96",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		97:
			# Level 97
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.01 PM (7).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 97",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		98:
			# Level 98
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.01 PM (8).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 98",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		99:
			# Level 99
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.01 PM (9).jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 99",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		100:
			# Level 100
			# Screenshot: WhatsApp Image 2026-10-06 at 6.47.01 PM.jpeg
			# TODO: Implement actual geometry from screenshot analysis
			return _lv(
				"Level 100",
				"Clear all rings to complete the level.",
				_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder
			)
		_:
			# Fallback for undefined levels
			return _lv("Level %d" % level_id, "Solve the puzzle.", _one(60.0, C, 90.0, 56.0, 120.0))

# Helper functions for level definition
static func _lv(title: String, instruction: String, root: Dictionary) -> Dictionary:
	return { "title": title, "instruction": instruction, "root": root }

static func _n(r: float, shape: int, gaps: int, turn: float, color: int, kids: Array, bridge: bool = false, extra: Array = []) -> Dictionary:
	return {
		"r": r, "shape": shape, "gaps": gaps, "turn": turn,
		"color": color, "kids": kids, "bridge": bridge, "extra": extra,
		"thick": 16.0
	}

static func _leaf(r: float, turn: float, gaps: int = 1) -> Dictionary:
	return _n(r, C, gaps, turn, 0, [])

static func _one(anchor: float, shape: int, angle: float, leaf: float, turn: float) -> Dictionary:
	return _n(anchor, shape, 1, 0.0, 0, [[angle, _leaf(leaf, turn)]])

static func _k(angle: float, radius: float, turn: float, children: Array = [], gaps: int = 1) -> Array:
	return [angle, _n(radius, C, gaps, turn, 0, children.duplicate())]

static func _closed(radius: float, shape: int, children: Array, bridge: bool = false, locks: Array = []) -> Dictionary:
	var node := _n(radius, shape, 0, 0.0, 0, children, bridge, [])
	if not locks.is_empty():
		node["locks"] = locks
	return node

static func _open_root(radius: float, turn: float, children: Array) -> Dictionary:
	return _n(radius, C, 1, turn, 0, children)

# TODO: Add remaining helper functions from original campaign_board.gd