#!/usr/bin/env python3
"""
Complete Level Extraction System for RotateRings
Extracts ALL levels from screenshots and generates replacement campaign_board.gd
"""

import os
import json
from pathlib import Path
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, asdict, field


@dataclass
class Ring:
    """Ring specification."""
    id: int
    radius: float
    shape: str  # 'C', 'S', 'T', 'O'
    gaps: int  # 0=closed, 1=one gap, 2=two gaps
    turn: float  # initial rotation in degrees
    color_name: str  # for reference
    thickness: float = 16.0


@dataclass
class Connection:
    """Parent-child connection."""
    parent_id: int
    child_id: int
    angle: float  # angle from parent to child


@dataclass
class Lock:
    """Lock between two rings on a closed hub."""
    ring_a: int
    ring_b: int


@dataclass
class Level:
    """Complete level specification."""
    level_id: int
    title: str
    instruction: str
    root_id: int
    rings: List[Ring] = field(default_factory=list)
    connections: List[Connection] = field(default_factory=list)
    locks: List[Lock] = field(default_factory=list)
    screenshot_file: str = ""


class LevelExtractor:
    """Extracts all levels from screenshots."""
    
    def __init__(self, screenshots_dir: str):
        self.screenshots_dir = Path(screenshots_dir)
        self.levels: Dict[int, Level] = {}
        self.screenshot_map: Dict[int, Path] = {}  # level_id -> file path
        
    def scan_all_screenshots(self):
        """Scan directory and map screenshots to level IDs."""
        files = sorted([f for f in self.screenshots_dir.glob("*.jpeg") 
                       if not f.name.endswith('.import')])
        
        print(f"Found {len(files)} screenshot files")
        
        # For now, assume files are in order for levels 2-100
        # We'll need to read each to get the actual level number
        for i, filepath in enumerate(files):
            estimated_level = i + 2  # Start at level 2
            self.screenshot_map[estimated_level] = filepath
            print(f"Mapped {filepath.name} to estimated level {estimated_level}")
    
    def extract_level_from_screenshot(self, level_id: int) -> Optional[Level]:
        """
        Extract level geometry from a screenshot.
        This is where we'd use vision AI to analyze the image.
        
        For now, returns a template that needs to be filled in manually.
        """
        filepath = self.screenshot_map.get(level_id)
        if not filepath:
            return None
        
        # Template level - needs actual analysis
        level = Level(
            level_id=level_id,
            title=f"Level {level_id}",
            instruction="Clear all rings to complete the level.",
            root_id=0,
            screenshot_file=filepath.name
        )
        
        # This is where vision analysis would extract rings, connections, locks
        # For now, return empty template
        return level
    
    def extract_all_levels(self):
        """Extract all levels from screenshots."""
        self.scan_all_screenshots()
        
        for level_id in sorted(self.screenshot_map.keys()):
            print(f"\nExtracting Level {level_id}...")
            level = self.extract_level_from_screenshot(level_id)
            if level:
                self.levels[level_id] = level
    
    def export_to_json(self, output_path: str):
        """Export extracted levels to JSON for review/editing."""
        data = {
            level_id: asdict(level) 
            for level_id, level in self.levels.items()
        }
        
        with open(output_path, 'w') as f:
            json.dump(data, f, indent=2)
        
        print(f"\nExported {len(self.levels)} levels to {output_path}")
    
    def generate_gdscript(self, output_path: str):
        """Generate complete campaign_board.gd replacement."""
        lines = [
            "extends RefCounted",
            "class_name CampaignBoard",
            "",
            "# AUTO-GENERATED from screenshots - ALL levels replaced",
            "# Generated by extract_all_levels.py",
            "",
            "const LevelDefinitionScript = preload(\"res://data/level_definition.gd\")",
            "const PieceDefinitionScript = preload(\"res://data/piece_definition.gd\")",
            "const GapDefinitionScript = preload(\"res://data/gap_definition.gd\")",
            "const LinkDefinitionScript = preload(\"res://data/link_definition.gd\")",
            "const SolutionStepScript = preload(\"res://data/solution_step.gd\")",
            "const Rules = preload(\"res://gameplay/puzzle_rules.gd\")",
            "const Geometry = preload(\"res://gameplay/piece_geometry.gd\")",
            "const RingPiece2DScript = preload(\"res://gameplay/ring_piece_2d.gd\")",
            "const ConnectorRuntime = preload(\"res://gameplay/connector_runtime.gd\")",
            "const BFSSolver = preload(\"res://tools/bfs_solver.gd\")",
            "",
            "const C := 0  # Circle",
            "const S := 1  # Square",
            "const T := 2  # Triangle",
            "const O := 3  # Oval",
            "",
            "const _PALETTE: Array[Color] = [",
            "\tColor(\"#32ADDA\"),  # Cyan",
            "\tColor(\"#EA7829\"),  # Orange",
            "\tColor(\"#7B61FF\"),  # Purple",
            "\tColor(\"#C8202F\"),  # Red",
            "\tColor(\"#2CA45C\"),  # Green",
            "\tColor(\"#4361CF\"),  # Blue",
            "\tColor(\"#F38224\"),  # Light Orange",
            "\tColor(\"#3EC6B0\"),  # Teal",
            "]",
            "",
            "const _BOARD := Vector2(360, 610)",
            "const _HALF := Vector2(292, 370)",
            "const _AIR := 34.0",
            "",
            "static var _cache: Dictionary = {}",
            "static var _defer_solve: bool = true",
            "",
            "static func build(level_id: int):",
            "\tif _cache.has(level_id):",
            "\t\treturn _cache[level_id]",
            "\tvar spec: Dictionary = _spec(level_id)",
            "\tvar root: Dictionary = spec.root",
            "\t_paint(root, level_id % _PALETTE.size(), -1)",
            "\tvar flat: Array = []",
            "\tvar edges: Array = []",
            "\t_walk(root, Vector2.ZERO, flat, edges)",
            "\t_fit(flat)",
            "\tvar def = LevelDefinitionScript.new()",
            "\tdef.level_id = level_id",
            "\tdef.chapter_id = 1 + int((level_id - 1) / 10)",
            "\tdef.title = spec.title",
            "\tdef.instruction = spec.instruction",
            "\tdef.pieces = _pieces_from(flat)",
            "\tdef.links = _links_from(flat, edges)",
            "\t_set_rest_angles(def)",
            "\t_stamp_solution(def)",
            "\t_cache[level_id] = def",
            "\treturn def",
            "",
            "static func _spec(level_id: int) -> Dictionary:",
            "\treturn _level_root(level_id)",
            "",
            "static func _level_root(level_id: int) -> Dictionary:",
            "\t# All levels extracted from screenshots",
            "\tmatch level_id:",
        ]
        
        # Add each level case
        for level_id in sorted(self.levels.keys()):
            level_lines = self._generate_level_case(self.levels[level_id])
            lines.extend(level_lines)
        
        lines.extend([
            "\t\t_:",
            "\t\t\t# Fallback for undefined levels",
            "\t\t\treturn _lv(\"Level %d\" % level_id, \"Solve the puzzle.\", _one(60.0, C, 90.0, 56.0, 120.0))",
            "",
            "# Helper functions for level definition",
            "static func _lv(title: String, instruction: String, root: Dictionary) -> Dictionary:",
            "\treturn { \"title\": title, \"instruction\": instruction, \"root\": root }",
            "",
            "static func _n(r: float, shape: int, gaps: int, turn: float, color: int, kids: Array, bridge: bool = false, extra: Array = []) -> Dictionary:",
            "\treturn {",
            "\t\t\"r\": r, \"shape\": shape, \"gaps\": gaps, \"turn\": turn,",
            "\t\t\"color\": color, \"kids\": kids, \"bridge\": bridge, \"extra\": extra,",
            "\t\t\"thick\": 16.0",
            "\t}",
            "",
            "static func _leaf(r: float, turn: float, gaps: int = 1) -> Dictionary:",
            "\treturn _n(r, C, gaps, turn, 0, [])",
            "",
            "static func _one(anchor: float, shape: int, angle: float, leaf: float, turn: float) -> Dictionary:",
            "\treturn _n(anchor, shape, 1, 0.0, 0, [[angle, _leaf(leaf, turn)]])",
            "",
            "static func _k(angle: float, radius: float, turn: float, children: Array = [], gaps: int = 1) -> Array:",
            "\treturn [angle, _n(radius, C, gaps, turn, 0, children.duplicate())]",
            "",
            "static func _closed(radius: float, shape: int, children: Array, bridge: bool = false, locks: Array = []) -> Dictionary:",
            "\tvar node := _n(radius, shape, 0, 0.0, 0, children, bridge, [])",
            "\tif not locks.is_empty():",
            "\t\tnode[\"locks\"] = locks",
            "\treturn node",
            "",
            "static func _open_root(radius: float, turn: float, children: Array) -> Dictionary:",
            "\treturn _n(radius, C, 1, turn, 0, children)",
            "",
        ])
        
        # Add the remaining helper functions from original file
        # (paint, walk, fit, pieces_from, links_from, set_rest_angles, etc.)
        # For now, include placeholder comment
        lines.append("# TODO: Add remaining helper functions from original campaign_board.gd")
        
        with open(output_path, 'w') as f:
            f.write('\n'.join(lines))
        
        print(f"\nGenerated GDScript to {output_path}")
    
    def _generate_level_case(self, level: Level) -> List[str]:
        """Generate match case for a single level."""
        lines = [f"\t\t{level.level_id}:"]
        
        # For now, generate placeholder
        # Real implementation would convert level.rings and level.connections
        # into the nested _n/_k/_closed structure
        
        lines.extend([
            f"\t\t\t# {level.title}",
            f"\t\t\t# Screenshot: {level.screenshot_file}",
            "\t\t\t# TODO: Implement actual geometry from screenshot analysis",
            "\t\t\treturn _lv(",
            f"\t\t\t\t\"{level.title}\",",
            f"\t\t\t\t\"{level.instruction}\",",
            "\t\t\t\t_one(60.0, C, 90.0, 56.0, 120.0)  # Placeholder",
            "\t\t\t)",
        ])
        
        return lines


def main():
    screenshots_dir = r"D:\AI secound Brain\RotateRings\ALL 2to100 levels"
    output_dir = Path(r"D:\AI secound Brain\RotateRings\tools\extracted_levels")
    output_dir.mkdir(exist_ok=True)
    
    extractor = LevelExtractor(screenshots_dir)
    
    print("=== RotateRings Level Extraction ===\n")
    
    # Extract all levels
    extractor.extract_all_levels()
    
    # Export to JSON for review
    json_path = output_dir / "extracted_levels.json"
    extractor.export_to_json(str(json_path))
    
    # Generate GDScript
    gd_path = output_dir / "campaign_board_new.gd"
    extractor.generate_gdscript(str(gd_path))
    
    print("\n=== Extraction Complete ===")
    print(f"Extracted {len(extractor.levels)} levels")
    print(f"JSON data: {json_path}")
    print(f"GDScript: {gd_path}")
    print("\nNext steps:")
    print("1. Review extracted_levels.json")
    print("2. Fill in actual geometry from screenshot analysis")
    print("3. Replace data/campaign_board.gd with campaign_board_new.gd")


if __name__ == '__main__':
    main()
